name: Run Tests

on: 
    push:
     branches:
     - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test
